# Generated by Django 4.2 on 2023-09-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=15)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_nonveg', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
