# Generated by Django 4.2 on 2023-10-28 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='donation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='donation_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
