# Generated by Django 4.2 on 2023-11-01 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_fooddonation_donation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='food_donation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.fooddonation'),
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.CharField(default='Erode', max_length=1000),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('volunteer', 'Volunteer'), ('ngo', 'NGO'), ('donor', 'Donor')], default='donor', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
