# Generated by Django 4.2 on 2023-11-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_total_price_order_food_donation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fooddonation'),
        ),
    ]
